### ISSUE TITLE
Is there any preprocessing to to be done

### ISSUE THREAD

**Issue by akarshsoman** [githubharald/WordDetectorNN#1]
i am working on scanned hand written documents which is more like form which has normal text and hand  written and when i pass a image to infer it detects even the normal text. So i would like to know whether pre- processing of the text is required 

![test](https://user-images.githubusercontent.com/25591311/107532471-f3628380-6be3-11eb-8dbc-58f20e924a34.jpg)

**Comment by githubharald** [comment]
no, there is no pre-processing required. The model seems to generalize pretty good to text, so that it also detects machine-printed text.
