### ISSUE TITLE
polygon detection instead of rectangle

### ISSUE THREAD

**Issue by seekingdeep** [githubharald/WordDetectorNN#10]
hi there,
Polygon detection can have a great impact when detecting text that is irregular or arbitrary shaped, even when the text is overlapping each other.
can WordDetectorNN be used to detect polygons?

**Comment by githubharald** [comment]
no, see: https://github.com/githubharald/WordDetectorNN/issues/5
I've used AABBs on purpose: because they are the simplest geometry suitable for text detection.
For many use-cases however, these AABBs are enough, e.g. for reading the text.
