### ISSUE TITLE
Detecting words using quadrilateral bounding boxes

### ISSUE THREAD

**Issue by seekingdeep** [githubharald/WordDetectorNN#12]
Hi,
1-  The training .xml files contain the annotation of each word, Does WordDetectorNN need word annotations?
Can't it only use pure quadrilateral bounding boxes x1,y1,x2,y2,x3,y3,x4,y4 for each word, while automatically setting 10% of that outer-part as a "word surrounding"?

2- How does WordDetectorNN method compares to (baseline) or perhaps (x-height+border) methods, such as [docExtractor](http://imagine.enpc.fr/~monniert/docExtractor/)?

3- Say, i am looking for a method that can handle both printed and handwritten text with high accuracy and efficiency,
- which method do you recommend pursuing: semantic segmentation or baseline or x-height+border or pixel level ....?
- how can the Connected Components be separated, such as text-lines with touching or overlapping components?

**Comment by githubharald** [comment]
you have to write your own dataset.py implementation, which returns image and AABB. Simply convert the x_i,y_i list to an AABB instance.
