### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by peleg122** [githubharald/WordDetectorNN#14]
trying to train/evaluate the model and i get after one epoch Segmentation fault (core dumped)
i tried to debug and i got the next message:
Fatal Python error: Segmentation fault

Thread 0x00007fda187fc700 (most recent call first):

Current thread 0x00007fdb9066a180 (most recent call first):
  File "/***/***//***/WordDetectorNN/src/coding.py", line 74 in func
  File "/***/***/***/WordDetectorNN/src/coding.py", line 89 in decode
  File "/***/***/***/WordDetectorNN/src/eval.py", line 81 in evaluate
  File "train.py", line 27 in validate
  File "train.py", line 97 in main
  File "train.py", line 107 in <module>

**Comment by githubharald** [comment]
that comes from OpenCV's cv2.connectedComponents function:
https://github.com/githubharald/WordDetectorNN/blob/master/src/coding.py#L74


* Dump the input which makes OpenCV crash to a file (using np.save) and upload it here, then I can check if it also crashes for me (and make sure it's not some garbage input like None)
* Other than that, I don't see a reason why OpenCV should crash (except if we feed some garbage input) - so then the issue should be reported to OpenCV

Meanwhile, you can try a different OpenCV version or use fg_by_threshold instead.

**Comment by peleg122** [comment]
using fg_by_threshold worked thanks !
