### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by bilal-24** [githubharald/WordDetectorNN#15]
Hi, Harald,

How can i use my gpu to train? I trained a model in my pc with iam handwriting database in cpu, but it spent too times. So, i want to train a model in my GPU(geforce rtx 2060). I could train your ctc word beam search and SimpleHTR in my GPU. Cuda and Cudnn etc. set up my pc.

**Comment by githubharald** [comment]
The word detector training script is written to use cuda by default. I also trained it with a RTX2060, so it should work.
Maybe you use the wrong pytorch version which does not support cuda? You can check with torch.cuda.is_available().
