### ISSUE TITLE
Segmentation fault (core dumped) infer.py

### ISSUE THREAD

**Issue by nrepesh** [githubharald/WordDetectorNN#16]
Getting a segmentation fault when running infer.py. As per instructions, I installed all requirements in a docker container and executed python infer.py. Is there a specific version of cv2 that I should be using? Looks like the segmentation fault is coming from 
```
loader = DataLoaderImgFile(Path('../data/test'), net.input_size, args.device)
```

**Comment by githubharald** [comment]
can you check if it is the same issue: https://github.com/githubharald/WordDetectorNN/issues/14

**Comment by nrepesh** [comment]
Unfortunately not, I'm getting this error in infer.py. I tried a few different versions of opencv. Where do you suggest we use fg_by_threshold?

**Comment by githubharald** [comment]
that's here: https://github.com/githubharald/WordDetectorNN/blob/master/src/eval.py#L81

which is also called from inter.py, so it might be the problem, let's see.
