### ISSUE TITLE
Addressing wrong element in orig.shape (dataloader.py) line 132

### ISSUE THREAD

**Issue by Jarr0d161** [githubharald/WordDetectorNN#17]
Hey,
first of all, thanks for the great work!

I had some troubles with high resolution line images (100px x 2000px).

I think in line 132 `f = min(self.max_side_len / orig.shape[0], self.max_side_len / orig.shape[0]` you want to address the second element: [https://github.com/githubharald/WordDetectorNN/blob/master/src/dataloader.py#L132](https://github.com/githubharald/WordDetectorNN/blob/master/src/dataloader.py#L132)

`f = min(self.max_side_len / orig.shape[0], self.max_side_len / orig.shape[1]`

KR,
Jonny

edit: same in line [145](https://github.com/githubharald/WordDetectorNN/blob/master/src/dataloader.py#L145)

**Comment by githubharald** [comment]
Hi Jonny, thanks for reporting 👍, I'll have a look asap.

**Comment by githubharald** [comment]
you're right - that was a bug, both width and height should be considered of course. Fixed it. Tested it locally. Can you also confirm everything works fine now for you?
