### ISSUE TITLE
Improve Model's Accuracy

### ISSUE THREAD

**Issue by bilal-24** [githubharald/WordDetectorNN#19]
Hello Harald, thanks for sharing.
I'm currently working on WordDetectorNN and I want to improve the model.
I'm not using the IAM dataset, I produced mine using a similar framework but using .npy files instead of .xml files for the coordinates.
I got better results but I need to increase much more my accuracy for my project.

Could you give me some tips to improve the model?
Thanks again.

![image](https://user-images.githubusercontent.com/76588928/171017023-f787b298-3810-4551-9240-6c7f0747a141.png)

**Comment by githubharald** [comment]
Hi,

just to rule out the NMS (aabb_clustering.py and coding.py) before digging deeper into model & data, I suggest you set max_aabbs to a really high number in infer.py. Further, you could try to disable NMS completely (immediately return the input to cluster_aabbs). Of course, things will get slow then, but at least you will see if a missed word is really missed by the model itself or if it was just removed by NMS.

**Comment by bilal-24** [comment]
Thank you so much Harald,

It helped me a lot.

Best regards...
