### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../model/weights'"

### ISSUE THREAD

**Issue by Saigha** [githubharald/WordDetectorNN#2]
Hi, I get the following error "FileNotFoundError: [Errno 2] No such file or directory: '../model/weights'" eaven if both the "metadata" and the "weights" file are in the model folder, am I missing something?

**Comment by githubharald** [comment]
The model paths are specified relative to the src directory, so you have to run the scripts from the src directory. 
Is this the case?

**Comment by Saigha** [comment]
I tried changing the path with an absolute one and is working now, it was probably a problem whit pycharm (lately I had some problem whit relative path), thanks anyway for your help
