### ISSUE TITLE
performance evaluation

### ISSUE THREAD

**Issue by ShadmanRohan** [githubharald/WordDetectorNN#4]
hi, is there any standard algorithm or metric to evaluate the performance of these models?

**Comment by githubharald** [comment]
There are multiple possibilities, maybe the simplest one is computing the intersection over union (IOU) between ground truth and detections, and counting every detection with IOU larger than some threshold (e.g. 70%) as true positive.
Then you can compute the standard measures Recall and Precision. 
Look at the EAST paper and the datasets used there. For each of them there usually is some evaluation protocol, e.g. for the ICDAR challenge.
