### ISSUE TITLE
Handwritten Text-Lines

### ISSUE THREAD

**Issue by seekingdeep** [githubharald/WordDetectorNN#5]
@githubharald Hi there,
Can this method be used to segment Handwritten Text-Lines?
note that Handwritten Text-Lines are polygon shaped, not rectangles. They are close to each other
![example](https://github.com/lolpa1n/digital-peter-ocrv/raw/master/pics/kozhanye.jpg)

**Comment by githubharald** [comment]
no, the method only works with axis-aligned rectangle shaped bounding boxes.

**Comment by seekingdeep** [comment]
So it can detect only words, and cant be trained to detect text-lines?

**Comment by githubharald** [comment]
if you retrain it, sure, it should be able to detect lines. It is important to have the lines almost axis-aligned (i.e. rotation ~0deg), so that a tight AABB can be fitted around the text-line.
But just give it a try, then you'll see if it works...
